details:
  - analysis: RNA-seq
    genome_build: GRCh37
    algorithm:
      aligner: star
resources:
  default:
    cores: 20
    jvm_opts:
    - -Xms750m
    - -Xmx1000m
    memory: 2G
upload:
  dir: ../final
